name: git-workflows 
channels:
  - conda-forge
dependencies:
  - ruby
  - python==3.7
  - pandas
  - numpy
  - matplotlib
  - scipy
  - jupyterlab
  - pip:
    - bash_kernel
    - -r ../requirements.txt
